import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import header from "@/components/header";
import Header from "@/components/header";


const jetbrainsMono = JetBrains_Mono ({subsets:
  ["latin"],
  weight:["100","200","300","400","500","600","700","800"],
  variable:"--font-jetbrainsMono"

})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${jetbrainsMono.variable}  antialiased`} >
          <Header/>
        {children}
      </body>
    </html>
  );
}
